POST http://localhost:8080/todo-list/
Authorization: user1
Content-Type: application/json

{
  "name": "Sample Todo List"
}

> {%
    client.test("Request executed successfully (Created - 201)", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
 client.global.set("lastId", response.body.identifier)
 %}

###

POST http://localhost:8080/todo-list/{{lastId}}/todo/
Authorization: user1
Content-Type: application/json

{
  "content": "Simple Todo"
}

> {%
    client.test("Request executed successfully (No Content - 201)", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
    client.global.set("lastTodoId", response.body.identifier)
%}

###

PUT http://localhost:8080/todo-list/{{lastId}}/todo/{{lastTodoId}}
Authorization: user1

> {%
    client.test("Request executed successfully (No Content - 202)", function() {
        client.assert(response.status === 202, "Response status is not 202");
    });
%}
