POST http://localhost:8080/todo/
Authorization: user1
Content-Type: application/json

{
  "name": "Todo2"
}

> {%
 client.global.set("lastId", response.body.identifier)
 %}

###

GET http://localhost:8080/todo/{{lastId}}
Authorization: user1

###

GET http://localhost:8080/todo/?query=Todo&page=0

###

DELETE http://localhost:8080/todo/{{lastId}}
Authorization: user1